title: "multixlab"
baseurl: ""

permalink:      /:title/
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

exclude: [README.md, Gemfile, Gemfile.lock, .idea, node_modules,
          gulpfile.js, package.json, _site, Makefile, src, vendor,
          CNAME, LICENSE, Rakefile]

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

theme: jekyll-theme-minimal